include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    prefer_single_quotes: true
    # avoid_print: true
    # always_use_package_imports: true
    # prefer_relative_imports: false
    # public_member_api_docs: false
    # omit_local_variable_types: false
    # lines_longer_than_80_chars: false
