include: package:effective_dart/analysis_options.1.3.0.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_relative_imports: false
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false